### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jstl-api#1]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by senivam** [comment]
master:
https://jenkins.eclipse.org/jstl/view/Build/job/Jersey_master_build_pipeline/
EE4J_8:
https://jenkins.eclipse.org/jstl/view/Build/job/Jersey_EE4J_build_pipeline/
