### ISSUE TITLE
Opening and closing quotes are inconsistent throughout the specification document

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#100]
For example two code examples:

1. `<c:out value="${customer.address.city}" default="unknown"/>`
This example uses straight double quotes.

2. `<c:set var=”foo” value=”value”/>`
This example uses curly quotes

We should at the very least be consistent in our examples.

I'm open to changing this to option 1 throughout but for typographical reasons some may disagree.

Thoughts on 1/2?

https://practicaltypography.com/straight-and-curly-quotes.html

**Comment by arjantijms** [comment]
+1 for straight double quotes, so 1.

**Comment by pnicolucci** [comment]
I'll start working on these changes today.
