### ISSUE TITLE
Update Jakarta Server Pages spec references in spec document.

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#114]
Update the following footnote to actually quote the Jakarta Server Pages spec document:

> .footnote:[It is important to note that the Jakarta Server Pages specification says that "A name should refer to a unique object at all points in the execution, that is all the different scopes really should behave as a single name space." The Jakarta Server Pages specification also says that "A JSP container implementation may or may not enforce this rule explicitly due to performance reasons". Because of this, if a scoped variable with the same name as a nested variable already exists in a scope other than 'page', exactly what happens to that scoped variable depends on how the Jakarta Server Pages container has been implemented. To comply with the Jakarta Server Pages specification, and to avoid non-portable behavior, page authors should therefore avoid using the same name in different scopes.]

We need to see how the Jakarta Server Pages spec actually words the above and copy that into the spec or give it a reference to a section in the specification as an alternative.

**Comment by pnicolucci** [comment]
Looking at the Jakarta Server Pages Specification: https://jakarta.ee/specifications/pages/3.0/jakarta-server-pages-spec-3.0.html#objects-and-scopes it states the following:

> A name should refer to a unique object at all points in the execution; that is, all the different scopes really should behave as a single name space. A JSP container implementation may or may not enforce this rule explicitly for performance reasons.

The only difference I see between the Jakarta Tags footnote and the Jakarta Server Pages specification is the use of `JSP` in the Jakarta Pages specification and it being spelled out in the Jakarta Tags Specification as "Jakarta Server Pages container"

**Comment by pnicolucci** [comment]
@volosied @arjantijms any thoughts on this one? Should we just leave it as we have it in the Tags Specification where we spell out "Jakarta Server Pages" or should we actually quote the Pages specification verbatim and use "JSP"?

**Comment by volosied** [comment]
I'm not too sure. We could probably leave the JSTL text as is as long as we source the section where the quote is found in the JSP spec?

**Comment by starksm64** [comment]
I agree with @volosied and would just include the section number and use the quote verbatim with the JSP usage:

The Jakarta Server Pages specification (1.8.2) also says that "A JSP container..."
