### ISSUE TITLE
Do we need to add a trademark for Java in the specification?

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#122]
There are a number of occurrences of : `Java class` in the spec document. Is this ok as is or do we need to add a trademark to these references?

**Comment by keilw** [comment]
Not sure, did you ask @ivargrimstad or @waynebeaton. Personally I think it would be an overkill. Mentioning the "TM" in the main project  description, sure that sounds reasonable but in a larger text where the word "Java class" is mentioned it feels over-exaggerated.

**Comment by waynebeaton** [comment]
It's actually Oracle's opinion that matters.

https://www.oracle.com/legal/trademarks.html

Add a trademark credit line in the document, and I believe that we're good-to-go.

**Comment by pnicolucci** [comment]
The current trademark credit line on the Oracle website is : `"Oracle, Java, and MySQL are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners."` so I'll work to add this to our specification.
