### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Standard Tag Library 2.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jstl-api#126]
- [x] Organization Name ("Organization") and, if applicable, URL
Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
[EE4J implementation of Jakarta Standard Tag Library 2.0.0](https://github.com/eclipse-ee4j/jstl-api/releases/download/2.0.0-IMPL-RELEASE/jakarta.servlet.jsp.jstl-2.0.0.jar)
- [x] Specification Name, Version and download URL
[Jakarta Standard Tag Library 2.0](https://jakarta.ee/specifications/tags/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
Promoted: [Jakarta Standard Tag Library 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-tags-tck-2.0.0.zip)
Final:  [Jakarta Standard Tag Library 2.0.0](https://download.eclipse.org/jakartaee/tags/2.0/jakarta-tags-tck-2.0.0.zip), SHA-256: 98f962da1a9c86fd1463ab8e65292cec7a7594ee000e14b4330bac8a34cfd355
- [x] Public URL of TCK Results Summary
[TCK results summary](https://eclipse-ee4j.github.io/jstl-api/certifications/jakarta-tags/2.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
None
- [x] Java runtime used to run the implementation
Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...
 Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL.](https://www.eclipse.org/legal/tck.php)
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by arjantijms** [comment]
Note: TCK results is pending PR https://github.com/eclipse-ee4j/glassfish/pull/23246 and will be moved at a later date to the jstl-api website.

The SHA is valid as-of 16 October 2020 and may change before the ballot starts.

**Comment by arjantijms** [comment]
TCK results now at https://eclipse-ee4j.github.io/jstl-api/certifications/jakarta-tags/2.0/TCK-Results

**Comment by kwsutter** [comment]
@arjantijms You have two SHA values for the TCK listed on this CR. The second one looks valid.  Can you remove the first one?  Thanks.

**Comment by arjantijms** [comment]
> You have two SHA values for the TCK listed on this CR. The second one looks valid. Can you remove the first one? Thanks.

Oops, copy/paste error somewhere. Thx!

**Comment by arjantijms** [comment]
As committer of Jakarta Standard Tag Library I assert this is complete and can be accepted.
