### ISSUE TITLE
Complete the Release of Tags 2.0

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jstl-api#136]
These are the remaining steps as per the spec-committee guide for the project team to complete to finalise the release of [Tags 2.0](https://github.com/jakartaee/specifications/pull/277):
  - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
  - [ ] go through the merged jakarta.ee specification website page to verify all the links are valid.
  - [x] approve the compatibility request.
  - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
  - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
API jar in Maven Central: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/2.0.0/

**Comment by arjantijms** [comment]
Links not all valid; PR to correct: https://github.com/jakartaee/specifications/pull/317

**Comment by arjantijms** [comment]
Links on https://jakarta.ee/specifications/tags/2.0/ now all valid.

**Comment by arjantijms** [comment]
Mail sent. CC'ed @pnicolucci
