### ISSUE TITLE
[TCK] c:import and BOM

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jstl-api#140]
Hi,

I'm trying to get Apache Tomcat/TomEE to pass the JSTL TCK, but I have one failure I haven't been able to fix.

Here is the JSP [https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/positiveImportEncodingNotSpecifiedTest.jsp](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/positiveImportEncodingNotSpecifiedTest.jsp)

Here is the expected result [https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/positiveImportEncodingNotSpecifiedTest.gf](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/positiveImportEncodingNotSpecifiedTest.gf)

The first file imported is [https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/encoding/Encoding.jsp](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/encoding/Encoding.jsp)

And the second [https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/import-encoded.txt](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jstl/spec/core/urlresource/importtag/import-encoded.txt)

In the golden file, there seems to be 2 extra characters.Here is the full log file for the test run
[https://tck.work/tomee/api/testlog/1218/1608116849515](https://tck.work/tomee/api/testlog/1218/1608116849515)

Any thoughts?
The result from Tomcat looks ok to me unless I missed something.
The 2 extra characters right in the middle are actually the BOM of the imported text file. This is a relative URL so it's served as a normal resource and therefore after reading the BOM, Tomcat (accurately?) strips the BOM from the response.

**Comment by kwsutter** [comment]
> In the golden file, there seems to be 2 extra characters.Here is the full log file for the test run
> https://tck.work/tomee/api/testlog/1218/1608116849515

I get this output when clicking on this URL:
`No such test 1608116849515 for task 1218`

**Comment by jeanouii** [comment]
Thanks @kwsutter 
That run is old and got purged.

Here is the log from the build last night

`04-09-2021 00:39:46:  [HttpRequest] Dispatching request: 'GET /jstl_core_url_import_web/positiveImportEncodingNotSpecifiedTest.jsp HTTP/1.1' to target server at 'localhost:39521'
04-09-2021 00:39:46:  TRACE: ########## The real value set: false
04-09-2021 00:39:46:  TRACE: [WIRE] - >> "GET /jstl_core_url_import_web/positiveImportEncodingNotSpecifiedTest.jsp HTTP/1.1[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - >> "User-Agent: Jakarta Commons-HttpClient/3.1[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - >> "Host: localhost:39521[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - >> "[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "HTTP/1.1 200 [\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "HTTP/1.1 200 [\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "Set-Cookie: JSESSIONID=A749EF07C44796E318B54EE55AB5CA07; Path=/jstl_core_url_import_web; HttpOnly[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "Content-Type: text/plain;charset=ISO-8859-1[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "Content-Length: 114[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "Date: Fri, 09 Apr 2021 00:39:46 GMT[\r][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\r][\n]"
04-09-2021 00:39:46:  TRACE: [Goldenfile] Loading goldenfile using encoding: ISO-8859-1
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "output from encoded jsp page[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[0x0]o[0x0]u[0x0]t[0x0]p[0x0]u[0x0]t[0x0] [0x0]f[0x0]r[0x0]o[0x0]m[0x0] [0x0]t[0x0]e[0x0]x[0x0]t[0x0] [0x0]f[0x0]i[0x0]l[0x0]e[0x0]:[0x0] [0x0]T[0x0]e[0x0]s[0x0]t[0x0] [0x0]P[0x0]A[0x0]S[0x0]S[0x0]E[0x0]D[0x0][\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - << "[\n]"
04-09-2021 00:39:46:  TRACE: [WIRE] - HttpConnectionManager is null.  Connection cannot be released.
04-09-2021 00:39:46:  ERROR: [TokenizedValidator]: Server's response and goldenfile to not match!

            Goldenfile token: ??�o�u�t�p�u�t�
            Response token:   �o�u�t�p�u�t�
04-09-2021 00:39:46:  ERROR: 
Server Response (below):
------------------------------------------










output from encoded jsp page




�o�u�t�p�u�t� �f�r�o�m� �t�e�x�t� �f�i�l�e�:� �T�e�s�t� �P�A�S�S�E�D�


------------------------------------------

Goldenfile (below):
------------------------------------------








    


output from encoded jsp page





??�o�u�t�p�u�t� �f�r�o�m� �t�e�x�t� �f�i�l�e�:� �T�e�s�t� �P�A�S�S�E�D�


------------------------------------------

04-09-2021 00:39:46:  ERROR: Test case throws exception: [BaseUrlClient] positiveImportEncodingNotSpecifiedTest failed! Check output for cause of failure.
04-09-2021 00:39:46:  ERROR: Exception at:  
04-09-2021 00:39:46:  ERROR: com.sun.ts.tests.common.webclient.TestFailureException: Test FAILED!
	at com.sun.ts.tests.common.webclient.WebTestCase.execute(WebTestCase.java:178)
	at com.sun.ts.tests.common.webclient.BaseUrlClient.invoke(BaseUrlClient.java:456)
	at com.sun.ts.tests.jstl.spec.core.urlresource.importtag.JSTLClient.positiveImportEncodingNotSpecifiedTest(JSTLClient.java:400)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:337)
	at com.sun.ts.tests.jstl.spec.core.urlresource.importtag.JSTLClient.run(JSTLClient.java:64)
	at com.sun.ts.tests.jstl.spec.core.urlresource.importtag.JSTLClient.main(JSTLClient.java:50)

04-09-2021 00:39:46:  [BaseUrlClient] Test cleanup OK`

**Comment by pnicolucci** [comment]
Hi, I've taken a look at this and the file that contains the Byte Order Mark (BOM) is the `import-encoded.txt` which is just a static file and not a Jakarta Server Pages page.

**Comment by jeanouii** [comment]
Hi @pnicolucci 

Thanks for the additional tests and thoughts.
For sure, I'll send that over now. Need to subscribe first.

**Comment by jeanouii** [comment]
@pnicolucci haven't heard back

**Comment by pnicolucci** [comment]
@jeanouii Let me work tomorrow to formulate some more formal thoughts on this. I need to perform some additional reviews of the test/specification and  then I'll share some additional thoughts/findings here as well as in the mailing lists.

**Comment by jeanouii** [comment]
@pnicolucci I reached out to Tomcat mailing list also to gather some thoughts on this ....
Here is the captured answer 


>> On 13/04/2021 20:17, Jean-Louis MONTEIRO wrote:
>> Hi guys,
>>
>> I have one JSTL issue and I'd need your feedback on it.
>> https://github.com/eclipse-ee4j/jstl-api/issues/140
>>
>> Can you guys have a look and let me know what you think?
>
> That looks like a side-effect of the various improvements we made to the
> Default Servlet to do a better job of including content with a variety
> of (potentially incompatible) encodings.
> 
> Generally, I'd expect the BoM to be skipped.
> 
> Historically, Tomcat didn't skip the BoM, so the original golden file
> was generated on that basis.
> 
> Mark

**Comment by jeanouii** [comment]
From a user perspective, I don't see by default any use case to keep the BOM

**Comment by pnicolucci** [comment]
Here is my take:

1) Jakarta Tags Specification Section 7.4 details the `<c:import>` tag:  [c:import](https://github.com/eclipse-ee4j/jstl-api/blob/master/spec/src/main/asciidoc/jakarta-stl.adoc#74-cimport)

Within this, it details the following: Character Encoding : The `<c:import/>` for `import-encoded.txt` does not include an encoding so the default encoding is used: `ISO-8859-1`

2) If I were to do the following: `<c:import url="import-encoded.txt" charEncoding="UTF-16"/>` then we would not see the BOM since the proper encoding is used and would see the actual text in the file rather than garbled characters which is what the test is actually looking for, see below.

This test is just checking the following:

```
<%-- If encoding is not specified, and no encoding is specified in the
     response of the imported resource, the default of ISO-8859-1
     will be used. --%>
```
     
As to whether or not to strip the BOM when the content type of the file uses a BOM and the content type being used does not use a BOM I disagree that it should be removed, and here is why:

- The encoding defaults to ISO-8859-1 which as far as I know doesn't use the BOM so just including the text as is in the `<c:import/>` seems reasonable to me.

- Tomcat remove the BOM from the file even when the `ISO-8859-1` encoding is used to read the `UTF-16` encoded text which I don't see how that improves anything.  It sounds like this is stripped outside of any Jakarta Tags or Jakarta Pages specification and is done as a specific change to Tomcat since Tomcat last was executed against the TCK.

At this point from a Jakarta Tags perspective, I believe the golden file is correct.

**Comment by jeanouii** [comment]
Thanks a lot Paul.

I'll circle back to Tomcat community and see what we can do

**Comment by dblevins** [comment]
@markt-asf I'd be interested in your perspective on this.

**Comment by pnicolucci** [comment]
@jeanouii is this issue still necessary? Thanks for the update!

**Comment by markt-asf** [comment]
The full discussion on the Tomcat dev list is here
https://tomcat.markmail.org/thread/cgwe5zizwg52cx6f

My reading is that this issue can be closed as INVAILD. The JSTL TCK is behaving correctly.

**Comment by pnicolucci** [comment]
Closing this issue given the latest comments!
