### ISSUE TITLE
Test Classes (/org/apache/taglibs/standard/lang/jstl/test) Packaged in Implementation Jar

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#142]
Hello,

The follow test classes are exported from the implementation:

https://github.com/eclipse-ee4j/jstl-api/tree/master/impl/src/main/java/org/apache/taglibs/standard/lang/jstl/test

Any particular reason they are included?

Looking at older versions (jakarta-taglibs-standard-1.0.2), I see these tests were also included:

http://archive.apache.org/dist/jakarta/taglibs/standard/binaries/

Otherwise, the documentation I found doesn't really clarify the need for them? 

https://tomcat.apache.org/taglibs/standard/testapidocs/org/apache/taglibs/standard/lang/jstl/test/package-summary.html

Thank you

**Comment by arjantijms** [comment]
I can't think of any specific reason for this, but we should look into it indeed. It doesn't feel right.
