### ISSUE TITLE
Tags 3.0: rename java.sun.com / xmlns.jcp.org taglib URIs to new jakarta.tags.* URNs

### ISSUE THREAD

**Issue by BalusC** [eclipse-ee4j/jstl-api#144]
In line with https://github.com/eclipse-ee4j/faces-api/issues/1553

Proposal: use URNs instead of URLs as URLs are more prone to confuse people because they expect them to be available as actual web resources along with XSDs. 

Also: remove "JSP" from new URIs as Jakarta Tags API allows it being reused in other view technologies than Jakarta Pages, such as Facelets.

E.g.

Rename `http://xmlns.jcp.org/jsp/jstl/core` to `jakarta.tags.core`
Rename `http://xmlns.jcp.org/jsp/jstl/fmt` to `jakarta.tags.fmt`

Then in JSP
```
<%@taglib prefix="c" uri="jakarta.tags.core" %>
<%@taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<html>
    ...
</html>
```

Or in Facelets
```
<html
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:c="jakarta.tags.core"
    xmlns:fmt="jakarta.tags.fmt"
>
    ...
</html>
```

Thoughts?

**Comment by BalusC** [comment]
FYI: I've proactively implemented support for `jakarta.tags.core` and `jakarta.tags.functions` for Faces 4.0: https://github.com/eclipse-ee4j/faces-api/issues/1553 This is because Faces uses internally the Facelets view technology which has its own implementation for the "core" and "functions" libraries of the Jakarta Tags API.

Old namespace URIs will keep working fine.

**Comment by pnicolucci** [comment]
@arjantijms @BalusC I'm working on the plan review for Jakarta EE10 for this project. See: https://www.eclipse.org/lists/jstl-dev/msg00063.html

Do we think this change requires a Tags 3.0 release or a Tags 2.1?  I see the title here refers to Tags 3.0 but just wanted to double-check that a change of this nature would be a change that warrants a major release.

**Comment by pnicolucci** [comment]
@volosied  we'll also want to ensure that the `tlddoc` looks correct once these changes are made.

**Comment by pnicolucci** [comment]
Also, we'll want to look at what TCK tests are available for testing these new changes and update where necessary. We can discuss that as we make progress with this issue.
