### ISSUE TITLE
Move impl/ folder to a separate project

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jstl-api#146]
The API now contains the implementation code. It should move to a new project, just like the Jakarta Pages impl code moved to WaSP.

**Comment by arjantijms** [comment]
Just a ping here, as we still need to do this.

@pnicolucci @volosied any suggestion for the name for such project?

What about:

* BadgeLy
* TagLy
* Mark

Multiple name proposals are needed, since Eclipse does a trademark scan for them and often a name can't be trademarked.

**Comment by pnicolucci** [comment]
Hey @arjantijms sorry I totally missed this last year. Can you give some context to the names you proposed?

**Comment by pnicolucci** [comment]
@arjantijms makes sense. Thanks for the context behind the names you presented. I don't have any objection to using these in the proposal. If I were to rank them in order of my favorite to least I'd say:

- TagLy
- BadgeLy
- Mark

**Comment by volosied** [comment]
@arjantijms  Just seeing notifications now. Sorry for missing this, too.

Suggestions above look good. Just for variety, the only two suggestion I propose are: 
- _TagLine_
- _MarkUp_

**Comment by arjantijms** [comment]
Thinking out loud, but instead of creating another project, an alternative could be copying the Tags /impl code to the WaSP project.

Wdyt?

**Comment by arjantijms** [comment]
@volosied @pnicolucci what do you think? It would save us quite a bit of hassle in the entire administration around creating a project, updating it, etc.

**Comment by pnicolucci** [comment]
I don't have an objection to that if the existing community is willing to have us :) 

Would we just merge the committers of the projects? Any object if I co-lead the project with you @arjantijms ?

**Comment by arjantijms** [comment]
> Any objection if I co-lead the project with you @arjantijms ?

No problem there. You are already committer on the WaSP project (see https://projects.eclipse.org/projects/ee4j.wasp/who). I've to look up the process again to see how to add a co-lead.

Looking at https://projects.eclipse.org/projects/ee4j.jstl/who I think it's only Volodymyr Siedlecki who would have to be added to WaSP.

**Comment by pnicolucci** [comment]
@arjantijms I think there are two more not on the WaSP project:

**Comment by pnicolucci** [comment]
@arjantijms  I think there are two more not on the WaSP project:

1) Jonathan Gallimore @jgallimore 
2) Jayasheelan Kumar @jayasheelankumar  - I'm not sure if he is still working on Jakarta EE though @edbratt  do you know?

For the project co-lead I think we just start a vote. There are multiple projects with co-leads.

**Comment by arjantijms** [comment]
@pnicolucci Thanks, I send out the 3 nominations. I'll wait for confirmation by @edbratt whether Jayasheelan Kumar is still active. I believe he wasn't anymore, but let's wait for the answer.

**Comment by volosied** [comment]
@arjantijms  Could you sent renominate me and Jonathan? We both didn't get enough votes. ```This election failed to receive the required number of votes in the alloted time.```

With you, Evan, and Paul, that should be enough votes (3 votes minimum, right?).  Thank you

**Comment by arjantijms** [comment]
@volosied The vote nomination concluded successfully this time: https://projects.eclipse.org/projects/ee4j.wasp/elections/election-volodymyr-siedlecki-committer-eclipse-wasp-0 :)

**Comment by anbusampath** [comment]
while reading https://projects.eclipse.org/projects/ee4j.wasp project description it mentioned as "Eclipse WaSP™ implements the Jakarta Pages and Jakarta Tag specifications. "

> Thinking out loud, but instead of creating another project, an alternative could be copying the Tags /impl code to the WaSP project.

is impl already moved WaSP project?

**Comment by arjantijms** [comment]
> is impl already moved WaSP project?

Not yet, but firmly on the TODO. We should really get this moving again, and I hope to do so this month.
