### ISSUE TITLE
Behavior differences with c:import when flushing out data

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#153]
Thanks to @Azquelt, we discovered a behavior difference between Apache Taglibs and this project.  Both Implementations use the org.apache.* classes, so I'm not sure of the history between the two?

Given the sample application, I would like to confirm which behavior is correct?

With Apache, there is no output with the the import statement. However, with Eclipse/Glassfish Impl, there is. 

test.jsp:
```
<%@ page session="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<TABLE border>
    <TR>
        <TD>Hello world</TD>
        <TD><%=System.currentTimeMillis()%></TD>
    </TR>
    <tr>
        <td>The import</td>
        <td><c:import url="imported-file.jsp" var="foo"/></td>
    </tr>
    <tr>
        <td>The output</td>
        <td><c:out value="${foo}"/></td>
    </tr>
</TABLE>
```

imported-file.jsp: 

```
<%@ page session="false" %>
Start of test a
<% out.flush(); %>
End of test a
```

Apache Taglibs: ( Tested on [1.2.5](https://repo1.maven.org/maven2/org/apache/taglibs/taglibs-standard-impl/1.2.5/)) 
![image](https://user-images.githubusercontent.com/5934310/128252563-d4608cd5-b67f-4c65-bc91-568d41664f1b.png)

Eclipse/Glassfish Taglibs: (Tested on [1.2.0](https://repo1.maven.org/maven2/org/glassfish/web/jstl-impl/1.2/) & [2.0.0](https://repo1.maven.org/maven2/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/)) 
![image](https://user-images.githubusercontent.com/5934310/128252764-65c3e2f3-6fe6-4eb7-8b70-b848f99a42cf.png)

Would appreciate any insight into this. Thank you

**Comment by volosied** [comment]
I've narrowed it down to the `ImportResponseWrapper` class. 

I think here?

Eclipse:
 https://github.com/eclipse-ee4j/jstl-api/blob/master/impl/src/main/java/org/apache/taglibs/standard/tag/common/core/ImportSupport.java#L461-L467
 
 Apache:
 https://github.com/apache/tomcat-taglibs-standard/blob/main/impl/src/main/java/org/apache/taglibs/standard/tag/common/core/ImportSupport.java#L482-L488

**Comment by markt-asf** [comment]
The import is to a variable so, in my view, the specification is clear that the variable should be set to the content of the resource. The presence of the `flush()` in the imported resource should not change that.

**Comment by volosied** [comment]
Hi @markt-asf, I appreciate the feedback! I agree with you, and I've made a PR to address this.  I guess I'll just wait and see what the JSTL community decides to do with it.

**Comment by pnicolucci** [comment]
I'll be working to create a 2.0.x branch as this is something that I believe should be delivered to both master (soon to be Tags 3.0.) and the 2.0.x branch so when / if we ever create a 2.0.1 release of Tags we'll have this same fix there.

@volosied once I have the 2.0.x branch created I'll let you know so you can create a PR against that branch as well.

I'll then send a final request for any feedback/objections to the mailing list and if no objections we'll merge this PR to both master and the 2.0.x branches.

Thanks!
