### ISSUE TITLE
Investigate impl/dependency-reduced-pom.xml

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#182]
https://github.com/eclipse-ee4j/jstl-api/blob/master/impl/dependency-reduced-pom.xml

We should take a closer look to see if this file is necessary or not. 

It may have been checked in by accident?  Its dependencies are outdated, and it appears to relate to a shaded jar. 

References: 
- https://stackoverflow.com/questions/22904573/what-is-the-purpose-of-dependency-reduced-pom-xml-generated-by-the-shade-plugin 
- https://stackoverflow.com/questions/35154717/is-dependency-reduced-pom-xml-automatically-used-instead-of-pom-xml

**Comment by pnicolucci** [comment]
The shaded prefix was updated in this POM here as a precaution: https://github.com/eclipse-ee4j/jstl-api/pull/181

**Comment by pnicolucci** [comment]
Deleting it looks to change nothing in the resulting built artifacts. A new dependency-reduced-pom.xml is generated in the impl/target directory.
