### ISSUE TITLE
Create Property To Use to Older Tag URIs in EE10

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#193]
See https://github.com/eclipse-ee4j/jstl-api/pull/172#issuecomment-995057435 and Arjan's reply.

We'll use this property temporarily as applications migrate to the new URIs.  

I'm thinking of a context parameter? 

Candidates Property Names: 
-  org.eclipse.useSunURIs
-  org.eclipse.useJavaSunURIs
- Please give suggestions :)

**Comment by joakime** [comment]
wouldn't this be an implementation concern and not something that the spec/api should worry about?

**Comment by volosied** [comment]
Turns out I was mistaken, Tags would not be able to support a property. It would need to be under JSP instead.
 For instance, in Tomcat, the [TLDScanner](https://github.com/apache/tomcat/blob/main/java/org/apache/jasper/servlet/TldScanner.java) searches for the TLDs. The JSP implementation should determine which TLDs are loaded or not.
The question now becomes whether we should be backward compatible. If so, then we will need to include another set of TLD files that use the older sun URIs. Developers would then be able to use either the jakarta.tags.* or the http://java.sun.com/jsp/jstl/* URIs. If not, then we can leave the code as it is now. 

Any thoughts? @pnicolucci @arjantijms

**Comment by volosied** [comment]
Personally, I think it's okay if we don't have backwards compatibility (especially if we remove older URI support in the next release after EE10). Plus, it's fairly simple to update the application to use the newer URIs. 

Any comments?

**Comment by joakime** [comment]
This seems like an issue for [eclipse-ee4j/wasp](https://github.com/eclipse-ee4j/wasp) to implement.
