### ISSUE TITLE
Port TLDDoc Code to JSTL-API Project

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#195]
While we can't move to [VLDDoc](https://github.com/eclipse-ee4j/jstl-api/issues/169), we can import the TLDDoc project code into jstl-api project after approval: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23881 

This would allow up to make the necessary updates to the TLDDoc to avoid various issues (javax references & TLD EE10 namespaces)..

**Comment by volosied** [comment]
Per comment 7 in the QC, we can check the source code in. Working on PR now.

**Comment by volosied** [comment]
Hi @starksm64 ,

As we switch our tlddoc  1.3 dependency to this newly ported code, the final implementation release jars will contain a reference to our new tlddoc in the pom.xml: `META-INF/maven.org.glassfish.web.jakarta.servlet.jsp.jstl/pom.xml`

As this pom will reference our local TLDDoc (proposed version 2.0), this project can't be built externally. Will this be a problem?  

Should we instead publish our version of tlddoc after all under new coordinates such as 

```
    <groupId>org.glassfish.web</groupId>
    <artifactId>jakarta.servlet.jsp.jstl.tlddoc</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
```

We're still brainstorming, but these are our current thoughts.  We might need to use different coordinates if the api and impl move to the same groupId. 

Let me know your thoughts. Thanks

**Comment by pnicolucci** [comment]
Hey Vlad, I'm trying to put the notion of us moving the tlds to the API project to rest. See the following issue with a link to a thread I started on the subject: https://github.com/eclipse-ee4j/jstl-api/issues/78

Looking at this closer I don't think we'll be able to depend on something that is not available out on maven central so we'll need to publish the tlddoc artifacts that we're using within the implementation. If someone tells me I'm incorrect here then that would be fine but to the best of my knowledge, we won't be able to just have it locally to this repo without publishing it.

In this PR currently, it would publish to the old tlddoc coordinates on maven central:

>     <artifactId>tlddoc</artifactId>
>     <name>taglibrarydoc</name>
>     <groupId>taglibrarydoc</groupId>

We don't want to do that as this is a new version of tlddoc that we're modifying for our use.

As such my proposal would be to publish this at the same coordinates as the implementation under a new artifactid.

**Comment by volosied** [comment]
@pnicolucci  I agree with you -- I've updated the tlddoc PR to publish under 
```
    <groupId>org.glassfish.web</groupId>
    <artifactId>tlddoc</artifactId>
```
