### ISSUE TITLE
Update TLD Attribute Infomation 

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#197]
We updated the URIs, but should we update any of the information below for EE10?  Version, Description, Display Name? 

https://github.com/eclipse-ee4j/jstl-api/blob/2f669f11a6948df5a01744ddf441b98c623103d4/impl/src/main/resources/META-INF/c.tld#L25-L29

**Comment by pnicolucci** [comment]
@volosied  perhaps a way to start this conversation is on the mailing list.
