### ISSUE TITLE
Automate JSTL Tests

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jstl-api#198]
PR #188 moved some tests to impl/src/test/java/*, but these tests aren't automated. 

It would be nice to update them to have them run during the maven build process or at least bundle them in a jar of them own?

**Comment by isaacrivriv** [comment]
Is anyone taking a look at this? If not, I can start hacking at this issue to try and get them running

**Comment by pnicolucci** [comment]
@isaacrivriv that would be great if you can take a look! Thank you!

**Comment by isaacrivriv** [comment]
Any documentation available on how these tests are supposed to run? Trying to get them to run locally but running into issues getting it to work. 

Mainly two issues I've been hitting
1. Running `StaticFunctionTests` I get `jakarta.servlet.jsp.JspException: An error occurred while evaluating custom action attribute "" with value "${foo:add(2, 3)}": org.apache.taglibs.standard.lang.jstl.parser.ParseException: EL functions are not supported. (null)`... Not sure if this test is specific to an older version?
3. Running `EvaluationTest` I get `Test failure - output file evaluationTestsRunOutput.txt differs from expected output file evaluationTestsOutput.txt`... Trying to compare the output of the tests with the output file already committed in the repo doesn't seem to match as expected.

Any ideas?

**Comment by volosied** [comment]
Thanks for helping out here Isaac! 


For 1, I think you need to set the following system propety to true. `jakarta.servlet.jsp.functions.allowed` ([link](https://github.com/eclipse-ee4j/jstl-api/blob/2a60c5505d3466c49e8f4ab1e49ef42ec0e5e7a3/impl/src/main/java/org/apache/taglibs/standard/lang/jstl/parser/ELParser.java#L721))

i.e. when running via command line:` java  -Djakarta.servlet.jsp.functions.allowed=true -cp 'jakarta.servlet.jsp.jstl-3.0.0-SNAPSHOT.jar':'jakarta.servlet.jsp-api-3.0.0.jar' 'StaticFunctionTests.java'`

**Comment by isaacrivriv** [comment]
Thanks Volodymyr! That worked out for 1. I'll check more in depth for the failures in 2 maybe there's something more specific that could help narrow down the error.
