### ISSUE TITLE
Update Scope Statement for Jakarta Server Pages Standard Tag Library Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jstl-api#21]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by waynebeaton** [comment]
How about this?

> Jakarta Standard Tag Library defines a framework and simple tags for Jakarta Server Pages that provide support for common, structural tasks such as iteration and conditionals, tags for manipulating XML documents, internationalization tags, and SQL tags.

**Comment by waynebeaton** [comment]
I optimistically declare lazy consensus (five days feels a little tight, but I don't see a different answer forthcoming).
