### ISSUE TITLE
Need draft PR for EE10

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jstl-api#213]
Hello, the deadline for individual component specifications to create a draft PR in the https://github.com/jakartaee/specifications project with candidate final API and specification is Feb 28. There does not need to be a complete PR with a compatible implementation. All that is required is to have the final candidate API staged, and to have a PR that include the candidate final specification. If your project cannot meet this deadline, it is possible it will miss the EE10 release train. Let the platform dev team(jakartaee-platform-dev@eclipse.org) or the EE10 release coordinator (sstark@redhat.com) when you will be able to create the PR, or if the EE10 platform should release with the previous version.

**Comment by pnicolucci** [comment]
@starksm64 I sent a note with a couple of questions: https://www.eclipse.org/lists/jstl-dev/msg00107.html

**Comment by starksm64** [comment]
@volosied you are a committer on the tags project, so you should have access to the https://ci.eclipse.org/jstl/ to stage releases. You could go ahead and stage a final 3.0.0 release and use that for the PR. This allows other dependent specs to reference the final version. If there are changes, the staged version can be dropped and restaged. If you have access problems to the https://ci.eclipse.org/jstl/ let me know.

**Comment by starksm64** [comment]
I just checked the PR and the staging repo:
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/

There is no staged 3.0.0 final yet. This was needed for the Feb 28 deadline. Please run the release staging job as there are no outstanding PRs.

**Comment by volosied** [comment]
@starksm64  @arjantijms  @pnicolucci   I've just staged the 3.0.0 API.  It's there now.

**Comment by starksm64** [comment]
Ok, thanks.
