### ISSUE TITLE
Change project name to Jakarta Server Pages Standard Tag Library

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jstl-api#22]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [ ]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by bshannon** [comment]
In the spirit of trying to find the simplest possible name, how about just "Jakarta Tag Library"?

**Comment by chkal** [comment]
I would prefer to keep "Standard" in the name to emphasize that it is just one tag library providing common standard functionality. 

But maybe we can drop the "Server Pages" part? So what about "Jakarta Standard Tag Library"?

**Comment by waynebeaton** [comment]
Poke.

Can the project team please vote or otherwise bring this to conclusion, please?

**Comment by waynebeaton** [comment]
Lazy consensus tells me that "Jakarta Standard Tag Library" is the name. I'll take that to the Specification Committee.
