### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Standard Tag Library 3.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jstl-api#226]
- [x] Organization Name ("Organization") and, if applicable, URL
Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Eclipse EE4J implementation of Jakarta Standard Tag Library 3.0.0](https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/3.0.0/jakarta.servlet.jsp.jstl-api-3.0.0.jar)
  [Eclipse GlassFish 7.0.0-M4](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/7.0.0-M4/glassfish-7.0.0-M4.zip)
- [x] Specification Name, Version and download URL
  [Jakarta Standard Tag Library 3.0](https://jakarta.ee/specifications/tags/3.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Standard Tag Library 3.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-tags-tck-3.0.0.zip), SHA-256: `996c9abc6561134cea986107da0648c2a33277d2f765475994ff9b16da70cb5a`
- [x] Public URL of TCK Results Summary
[TCK results summary](https://glassfish.org/certifications/jakarta-tags/3.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
None
- [x] Java runtime used to run the implementation
 OpenJDK 11.0.2, 17.0.1, 18-ea
- [x] Summary of the information for the certification environment, operating system, cloud, ...
 Debian GNU/Linux 10
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL.](https://www.eclipse.org/legal/tck.php)
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by volosied** [comment]
@arjantijms  Who should approve this compatibility request (item 4 of https://github.com/eclipse-ee4j/jstl-api/issues/230) ? 

I also verified the sha256 hashes match the site: 
```
openssl sha256 jakarta-tags-tck-3.0.0.zip 
SHA256(jakarta-tags-tck-3.0.0.zip)= 996c9abc6561134cea986107da0648c2a33277d2f765475994ff9b16da70cb5a 
```

**Comment by arjantijms** [comment]
@volosied I think it's best if @pnicolucci would assert the CCR is complete. I can send the email, I'll cc you and @pnicolucci.

**Comment by pnicolucci** [comment]
@arjantijms @volosied  this looks good to me! Here is my +1.

**Comment by pnicolucci** [comment]
Approved and closing.
