### ISSUE TITLE
Final prep for releasing Tags 3.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse-ee4j/jstl-api#230]
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by volosied** [comment]
- All links look valid: https://jakarta.ee/specifications/tags/3.0/
- No remaining PRs for 3.0

**Comment by arjantijms** [comment]
Mail has been send.

**Comment by pnicolucci** [comment]
The CCR here: https://github.com/eclipse-ee4j/jstl-api/issues/226 is complete. @arjantijms @volosied  do I just need to close out that issue or is there any other action?

**Comment by pnicolucci** [comment]
I approved the CCR and closed the issue.

**Comment by arjantijms** [comment]
API available in central: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/3.0.0/
