### ISSUE TITLE
Prepare Jakarta Standard Tag Library for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jstl-api#31]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by edbratt** [comment]
* javadoc and text updated - yes
* specification generated(https://github.com/eclipse-ee4j/jstl-api/tree/master/spec) - yes
 * staging release available(http://central.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/1.2.5/) -yes
* TCK test results passed(run manually and all tests cases(total 541) passed ) - yes

**Comment by m0mus** [comment]
See a PR here: https://github.com/jakartaee/specifications/pull/22
Task is completed

**Comment by m0mus** [comment]
Reopening because new tasks were added.
