### ISSUE TITLE
Update Eclipse GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jstl-api#34]
Update Eclipse GlassFish to use the new version of your API (and implementation, if applicable) by submitting a PR to [GlassFish](https://github.com/eclipse-ee4j/glassfish).

Although a new version of GlassFish will not be released for Jakarta EE 8, we hope to release an update sometime later.

**Comment by ruolli** [comment]
Jakarta Standard Tag Library 1.2.5 has been integrated to GF via https://github.com/eclipse-ee4j/glassfish/pull/22801 . Closing this issue.
