### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Standard Tag Library

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/jstl-api#35]
- [x] Organization Name ("Organization") and, if applicable, URL
Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
EE4J implementation of Jakarta Standard Tag Library 1.2.7
- [x] Specification Name, Version and download URL
[Jakarta Standard Tag Library 1.2](https://jakarta.ee/specifications/tags/1.2/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta Standard Tag Library TCK 1.2.0](https://download.eclipse.org/jakartaee/tags/1.2/eclipse-tags-tck-1.2.0.zip), SHA-256: af8b39153c0f0cae36f85b8792b9c678791cf59b41bd124a53f5205cd0a83e6a
- [x] Public URL of TCK Results Summary
[TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-tags/1.2/TCK-Results)
- [x] Any Additional Specification Certification Requirements
None
- [x] Java runtime used to run the implementation
Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...
 Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL.](https://www.eclipse.org/legal/tck.php)
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by bshannon** [comment]
The TCK results summary needs to link to a page hosted by the Compatible Implementation project, not a Jenkins page.
If necessary, you can link to this page:
https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-tags/1.2/TCK-Results

**Comment by ren-zhijun-oracle** [comment]
> The TCK results summary needs to link to a page hosted by the Compatible Implementation project, not a Jenkins page.
> If necessary, you can link to this page:
> https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-tags/1.2/TCK-Results

fixed, thanks!

**Comment by edbratt** [comment]
Updated TCK URL to point at final download location.
