### ISSUE TITLE
Deliver jstl-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jstl-api#42]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [x] **Initiate a ballot for your Jakarta Release Record/Plan.**
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by pnicolucci** [comment]
Jakarta Standard Tag Library 2.0.0 Release Record: https://projects.eclipse.org/projects/ee4j.jstl/releases/2.0.0 I marked the first two items off the check list here. As long as we stick to the Jakarta EE 9 overall release plan we won't need an additional review/ballot.

**Comment by arjantijms** [comment]
@pnicolucci is working on the spec doc conversion: https://github.com/eclipse-ee4j/jstl-api/commits?author=pnicolucci

**Comment by arjantijms** [comment]
Jakartified impl. in https://github.com/eclipse-ee4j/jstl-api/commit/885432cd1721a8a859245883421b3b33a3eb8cb0#diff-86ccec3d9ff0e9c0514506e982cdc08b

Note that implementation will move to https://github.com/eclipse-ee4j/wasp

**Comment by arjantijms** [comment]
Jakartified Tck in https://github.com/eclipse-ee4j/jakartaee-tck/commit/4029adc225dfddfe02180d24b02d533684dcd345

**Comment by kwsutter** [comment]
One last request for the Specifications PR to promote the Milestone deliverables for this Project.  The PR is created against the [Jakarta EE specifications github repo](https://github.com/jakartaee/specifications/pulls).  A template is automatically used when creating PRs against this repo which should help with understanding the steps required for a successful merge.  We're not looking for perfection for this Milestone.  We just want the ability to promote the great work that all of the Projects are doing.

If you submit a PR, please feel free to move this Epic to the [Milestone 1 Ready column in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-9442495).  Thanks!

**Comment by arjantijms** [comment]
@pnicolucci is still working on the spec doc, but nearly there. At chapter 15 of 16 now (and an appendix with compatibility and one with changes).

**Comment by pnicolucci** [comment]
We have the following Specification document issues opened for additional investigation:

1) https://github.com/eclipse-ee4j/jstl-api/issues/60

**Comment by arjantijms** [comment]
I think #60 is basically resolved. Ivar answers, and it's "Java SE™️" for the first usage, "Java SE" afterwards.

**Comment by arjantijms** [comment]
@pnicolucci Shall I do the specification PR with the current version of the document anyway? It's doesn't have to be perfect yet. E.g. Faces needs addressing a bunch of issues still, but I submitted the current version as a PR anyway. The remaining issues can be fixed for M2 (if any) or the final release.

**Comment by pnicolucci** [comment]
@arjantijms  I'm going to do some more clean up work today then I think we will be good to go. I'll add you as a reviewer as I go. Thanks!

**Comment by pnicolucci** [comment]
Working to merge the oracle spec directory into spec, hoping to have a PR later this evening @arjantijms .

**Comment by kwsutter** [comment]
Bump... Any word on creating the Draft Specification PR for JSTL?  This is one of three remaining PRs (JSTL, JSP, JSF).  Thanks!

**Comment by arjantijms** [comment]
@kwsutter 

Always something still to do for JSTL, but we have to draw the line somewhere. I'll create the PR momentarily.

**Comment by arjantijms** [comment]
Draft Specification and Apidoc PRs ready for review: https://github.com/jakartaee/specifications/pull/277

**Comment by arjantijms** [comment]
Ballot concluded successfully: https://www.eclipse.org/lists/jakarta.ee-spec/msg01276.html

**Comment by arjantijms** [comment]
Release review concluded successfully: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567944

**Comment by arjantijms** [comment]
Release steps concluded. I think this issue can be closed now.
