### ISSUE TITLE
Investigate adding Chapter 16 Java APIs

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#66]
This  Chapter from the original specification states the following:

> This chapter describes the Java APIs exposed by the JSTL specification. The content
> of this chapter is generated automatically from Javadoc annotations embedded into
> the actual Java classes and interfaces of the implementation. This ensures that both
> the specification and implementation are synchronized.

Currently this information isn't in the specification document. We need to determine as a project if we want to add this javadoc type information to the specification document. If we decide to we need to determine the best way to do so.

**Comment by arjantijms** [comment]
I think this was discussed a while ago on the platform list, and the strong consensus was to not include Javadocs in the specification anymore. The Javadoc is easily available, and duplicating it makes little sense.

**Comment by pnicolucci** [comment]
Closing as we've come to an agreement not to add the JavaDoc to the specification.
