### ISSUE TITLE
Determine if Updated Appendix B: Changes should be kept or removed

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#68]
Do we want to keep the old change log or start fresh?

**Comment by arjantijms** [comment]
I'm personally a big fan of change logs and kept the ones for the security specs, but I think most other teams have removed it.

The change log is of course never really gone, as it lives on in the JCP/Oracle version of the document, which does't just disappear.

**Comment by pnicolucci** [comment]
I've cleaned up the change log and reset it. I think it is cleaner in this instance as it's very difficult to remove acronyms for older version references of particular specifications.
