### ISSUE TITLE
Determine how to reference Java APIs in the spec document

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#70]
In the specification document there are a number of references to `link:jstl.html#UNKNOWN[See Java APIs]`

This is to point to Chapter 16 of the original specification document which lists all the JavaDoc of the APIs.

We need to determine how best to reference this in the Spec Doc now that we are not keeping Chapter 16, see #66

**Comment by arjantijms** [comment]
I just inserted the name of the method or class that's being referenced in italics. If not clear from the context you can use fully qualified class names.

**Comment by pnicolucci** [comment]
Yea that makes sense, thanks for the input!

**Comment by pnicolucci** [comment]
I believe we're all set here with the updates that have already been done. I'll close this issue out now.
