### ISSUE TITLE
Determine how to reference : JavaServer™ Pages (JSP™)

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#72]
There are multiple spots in the specification that having the following:

1) `JavaServer™ Pages (JSP™)`
2) `JavaServer Pages™`

Of course this needs to be `Jakarta Server Pages` / `JSP` however do we still need to add the TM to these?

Any input?

**Comment by arjantijms** [comment]
I think not, as we're referencing our own technology. I don't think I've seen it anywhere else in the converted specs.

Note that the agreement with Oracle also included not using "JSP" anymore. So it would be only "Jakarta Server Pages".

**Comment by pnicolucci** [comment]
Closing as we've come to an agreement here.
