### ISSUE TITLE
Determine if we should move tlds and doc generation to API

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#78]
This came up as part of : https://github.com/eclipse-ee4j/jstl-api/pull/76

**Comment by pnicolucci** [comment]
https://github.com/eclipse-ee4j/jstl-api/issues/141 looks related to this as well.

**Comment by pnicolucci** [comment]
This looks like it might have been the same as it is now all the way back in javax 1.2: https://repo1.maven.org/maven2/javax/servlet/jsp/jstl/jstl-api/1.2/

**Comment by pnicolucci** [comment]
Mailing list discussion: [Proposal to keep tlds in Implementation](https://www.eclipse.org/lists/jstl-dev/msg00100.html)

**Comment by volosied** [comment]
Per Paul's reasoning in the email above (TLDs are implementation specific) , the TLDs should stay in the implementation, and not be moved the API.
