### ISSUE TITLE
JSTL API needs a new RC2

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jstl-api#87]
Current RC1 references EL 4.0.0-SNAPSHOT version in the Manifest file. This needs correcting.

**Comment by arjantijms** [comment]
RC2 is now available here: 

https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/2.0.0-RC2/
