### ISSUE TITLE
Manifest is a mess for the RC2

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jstl-api#88]
OSGI manifest is not correct.

It imports package `jakarta.servlet.jsp.jstl.core` which is provided in the bundle and it imports it at a version different to the bundle.
It exports its packages as 2.0.0 but declares the bundle version as 2.0.0.RC2.

Once corrected the impl also needs correcting and release.

```Manifest-Version: 1.0
Bundle-Description: Jakarta Standard Tag Library API
Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.
 org/software/classpath/license.html
Bundle-SymbolicName: jakarta.servlet.jsp.jstl-api
Implementation-Version: 2.0.0-RC2
Built-By: jenkins
Specification-Vendor: Eclipse Foundation
Bnd-LastModified: 1594925012400
Bundle-ManifestVersion: 2
Bundle-DocURL: https://www.eclipse.org
Bundle-Vendor: Eclipse Foundation
Import-Package: jakarta.el;version="[4.0,5)",jakarta.servlet;version="
 [5.0,6)",jakarta.servlet.http;version="[5.0,6)",jakarta.servlet.jsp;v
 ersion="[3.0,4)",jakarta.servlet.jsp.jstl.core,jakarta.servlet.jsp.ta
 gext;version="[3.0,4)",javax.xml.parsers,org.xml.sax,org.xml.sax.help
 ers
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.2.0.201903051501
Implementation-Vendor: Eclipse Foundation
Export-Package: jakarta.servlet.jsp.jstl.core;uses:="jakarta.el,jakart
 a.servlet,jakarta.servlet.http,jakarta.servlet.jsp,jakarta.servlet.js
 p.tagext";version="2.0.0",jakarta.servlet.jsp.jstl.sql;version="2.0.0
 ",jakarta.servlet.jsp.jstl.tlv;uses:="jakarta.servlet.jsp.tagext";ver
 sion="2.0.0",jakarta.servlet.jsp.jstl.fmt;uses:="jakarta.servlet.jsp"
 ;version="2.0.0"
Bundle-Name: Jakarta Standard Tag Library API
Bundle-Version: 2.0.0.RC2
Extension-Name: jakarta.servlet.jsp.jstl
Build-Jdk-Spec: 1.8
Created-By: Apache Maven Bundle Plugin
Specification-Version: 2.0-SNAPSHOT
Build-Jdk: 1.8.0_202
```

**Comment by arjantijms** [comment]
After a quick glance at the API's pom.xml it's clear it's not using the spec version maven plugin and sets some of the manifest entries directly using the jar-plugin.

As a start I'll bring this inline with how most of the other projects are generating the manifest.

**Comment by arjantijms** [comment]
Using the spec version plug-in I get the following manifest:

```
unzip -p jakarta.servlet.jsp.jstl-api-2.0.0-RC3.jar META-INF/MANIFEST.MF

Manifest-Version: 1.0
Bundle-Description: Jakarta Standard Tag Library 2.0 Specification
Automatic-Module-Name: java.servlet.jsp.jstl
Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.
 org/software/classpath/license.html
Bundle-SymbolicName: jakarta.servlet.jsp.jstl-api
Implementation-Version: 2.0.0
Built-By: arjan
Bnd-LastModified: 1595012873483
Bundle-ManifestVersion: 2
Specification-Vendor: Eclipse Foundation
Implementation-Vendor-Id: org.glassfish
Bundle-DocURL: https://www.eclipse.org
Bundle-Vendor: Eclipse Foundation
Import-Package: jakarta.el;version="[4.0,5)",jakarta.servlet;version="
 [5.0,6)",jakarta.servlet.http;version="[5.0,6)",jakarta.servlet.jsp;v
 ersion="[3.0,4)",jakarta.servlet.jsp.jstl.core,jakarta.servlet.jsp.ta
 gext;version="[3.0,4)",javax.xml.parsers,org.xml.sax,org.xml.sax.help
 ers
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.2.0.201903051501
Implementation-Vendor: Eclipse Foundation
Export-Package: jakarta.servlet.jsp.jstl.tlv;uses:="jakarta.servlet.js
 p.tagext";version="2.0.0",jakarta.servlet.jsp.jstl.core;uses:="jakart
 a.el,jakarta.servlet,jakarta.servlet.http,jakarta.servlet.jsp,jakarta
 .servlet.jsp.tagext";version="2.0.0",jakarta.servlet.jsp.jstl.fmt;use
 s:="jakarta.servlet.jsp";version="2.0.0",jakarta.servlet.jsp.jstl.sql
 ;version="2.0.0"
Bundle-Name: Jakarta Standard Tag Library API
Bundle-Version: 2.0.0
Extension-Name: jakarta.servlet.jsp.jstl
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_191
Specification-Version: 2.0
```

**Comment by arjantijms** [comment]
p.s. the OSGi spec says the following about importing exported packages:


Importing Exported Packages

Bundles that collaborate require the same classloader for types used in the collaboration. If multiple bundles export packages with collaboration types then they will have to be placed in disjoint class- spaces, making collaboration impossible. Collaboration is significantly improved when bundles are willing to import exported packages; these imports will allow a framework to substitute exports for imports.

Though substitution is recommended to increase collaboration, it is not always possible. Importing exported packages can only work when those packages are pure API and not encumbered with implementation details. Import of exported packages should only be done when:

• The exported package does not use private packages. If an exported package uses private packages then it might not be substitutable and is therefore not clean API.
• There is at least one private package that references the exported package. If no such reference exist, there is no purpose in importing it.

In practice, importing exported packages can only be done with clean API-implementation separa- tion. OSGi services are carefully designed to be as standalone as possible. Many libraries intertwine API and implementation in the same package making it impossible to substitute the API packages.
Importing an exported package must use a version range according to its compatibility requirements, being either a consumer or a provider of that API. See Semantic Versioning on page 45 for more infor- mation.

**Comment by smillidge** [comment]
Where is this import coming from 

`jakarta.servlet.jsp.jstl.core,jakarta.servlet.jsp.tagext;version="[3.0,4)"`?

**Comment by smillidge** [comment]
Maybe it is OK but I think GlassFish needs a consistent set of all these interelated JSP, JSTL, EL apis and implementations.

**Comment by arjantijms** [comment]
> jakarta.servlet.jsp.jstl.core,jakarta.servlet.jsp.tagext;version="[3.0,4)"?

`jakarta.servlet.jsp.tagext;version="[3.0,4)"` at least is a regularly imported package. It's actually used in the API in several places.

`jakarta.servlet.jsp.jstl.core` looks like OSGi trying to be clever and seeing it being used in other bundles as a "collaborating bundle", though not 100% sure what triggers it.

**Comment by arjantijms** [comment]
A quick search reveals that `jakarta.servlet.jsp.jstl.core` is essentially used in Mojarra, but not in Servlet, JSP or EL seemingly.

**Comment by smillidge** [comment]
Actually the manifest may be OK the problem is that the manifest of the impl is explicitly importing the .RC1 api version and changing it to just import 2.0.0 is enough to make it work. It's probably the impl that needs work as all the imports are including the fourth . release.
https://jakarta.oss.sonatype.org/service/local/repositories/staging/archive/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0-M1/jakarta.servlet.jsp.jstl-2.0.0-M1.jar/!/META-INF/MANIFEST.MF

**Comment by arjantijms** [comment]
A quick (not much tested) API RC3 and an implementation M2 staged:

* https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/2.0.0-RC3/
* https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0-M2/

**Comment by smillidge** [comment]
They seem to work, thanks.
