### ISSUE TITLE
Finish footnote updates in spec document

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#94]
Finish the remaining work document in https://github.com/eclipse-ee4j/jstl-api/pull/93

**Comment by arjantijms** [comment]
Work seems to have finished in https://github.com/eclipse-ee4j/jstl-api/pull/93

**Comment by pnicolucci** [comment]
@arjantijms there is actually still a bit of work to complete here as I outlined in https://github.com/eclipse-ee4j/jstl-api/pull/93#issue-455849573

I'll try to get this done this week.
