### ISSUE TITLE
Clean up the remaining EL/JSP/JSTL acronyms in the specification document

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#97]
The remaining acronyms need to be fully qualified or changed in the spec document.

Many of these are in the backward compatibility section and then "Acknowledgments" section.

**Comment by arjantijms** [comment]
@pnicolucci did you already started working on this? If not, I can take a look at this.

**Comment by pnicolucci** [comment]
@arjantijms  no I didn't start this one yet.

There are some spots where the spec doc references the Jakarta Server Pages spec doc for instance:

> 
.footnote:[It is important to note that the Jakarta Server Pages specification says that "A name should refer to a unique object at all points in the execution, that is all the different scopes really should behave as a single name space." The Jakarta Server Pages specification also says that "A JSP container implementation may or may not enforce this rule explicitly due to performance reasons". Because of this, if a scoped variable with the same name as a nested variable already exists in a scope other than 'page', exactly what happens to that scoped variable depends on how the Jakarta Server Pages container has been implemented. To comply with the Jakarta Server Pages specification, and to avoid non-portable behavior, page authors should therefore avoid using the same name in different scopes.]

The above was what sparked my email:  https://www.eclipse.org/lists/jsp-dev/msg00131.html

So we may have to do some clean up in the Jakarta Server Pages spec doc as well to get our quotes in the Jakarta Standard Tag Library spec doc correct.

**Comment by arjantijms** [comment]
> Many of these are in the backward compatibility 

As we don't have backward compatibility here, I wonder if we should not remove that section.
